//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogLogViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogLogViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   LogLogViewer is a free soft. This software comes with no warranties. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutBoxMessage {
            get {
                return ResourceManager.GetString("AboutBoxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Infomation of {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutBoxTitle {
            get {
                return ResourceManager.GetString("AboutBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutBoxVersion {
            get {
                return ResourceManager.GetString("AboutBoxVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap arrow_090 {
            get {
                object obj = ResourceManager.GetObject("arrow_090", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap arrow_270 {
            get {
                object obj = ResourceManager.GetObject("arrow_270", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap clipboard_paste {
            get {
                object obj = ResourceManager.GetObject("clipboard_paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap clock {
            get {
                object obj = ResourceManager.GetObject("clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap color_swatch {
            get {
                object obj = ResourceManager.GetObject("color_swatch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap control {
            get {
                object obj = ResourceManager.GetObject("control", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap control_pause {
            get {
                object obj = ResourceManager.GetObject("control_pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap disk_return_black {
            get {
                object obj = ResourceManager.GetObject("disk_return_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap document_copy {
            get {
                object obj = ResourceManager.GetObject("document_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap edit_family {
            get {
                object obj = ResourceManager.GetObject("edit_family", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageBoxTitle {
            get {
                return ResourceManager.GetString("ErrorMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageFileNotFound {
            get {
                return ResourceManager.GetString("ErrorMessageFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File is empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageFileReadError {
            get {
                return ResourceManager.GetString("ErrorMessageFileReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap folder_open_document_text {
            get {
                object obj = ResourceManager.GetObject("folder_open_document_text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap funnel {
            get {
                object obj = ResourceManager.GetObject("funnel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap gear {
            get {
                object obj = ResourceManager.GetObject("gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Alert Mail に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string gridViewColumnHeaderAlertMail {
            get {
                return ResourceManager.GetString("gridViewColumnHeaderAlertMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string gridViewColumnHeaderColor {
            get {
                return ResourceManager.GetString("gridViewColumnHeaderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string gridViewColumnHeaderComment {
            get {
                return ResourceManager.GetString("gridViewColumnHeaderComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string gridViewColumnHeaderEnable {
            get {
                return ResourceManager.GetString("gridViewColumnHeaderEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string gridViewColumnHeaderMailEdit {
            get {
                return ResourceManager.GetString("gridViewColumnHeaderMailEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string gridViewColumnHeaderNo {
            get {
                return ResourceManager.GetString("gridViewColumnHeaderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regular Exp. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string gridViewColumnHeaderRegExp {
            get {
                return ResourceManager.GetString("gridViewColumnHeaderRegExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icon32 {
            get {
                object obj = ResourceManager.GetObject("icon32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Do you want to read again? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoMessageChangeEncoding {
            get {
                return ResourceManager.GetString("InfoMessageChangeEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The text you specified was not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoMessageFindNotFound {
            get {
                return ResourceManager.GetString("InfoMessageFindNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap magnifier {
            get {
                object obj = ResourceManager.GetObject("magnifier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap mail {
            get {
                object obj = ResourceManager.GetObject("mail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Please enter all of the items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MailDlgBlankError {
            get {
                return ResourceManager.GetString("MailDlgBlankError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-mail account has not yet been set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MailDlgSmtpError {
            get {
                return ResourceManager.GetString("MailDlgSmtpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   During transmission, an error has occurred. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MailDlgTestMailError {
            get {
                return ResourceManager.GetString("MailDlgTestMailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test email was sent. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MailDlgTestMailSend {
            get {
                return ResourceManager.GetString("MailDlgTestMailSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon multi {
            get {
                object obj = ResourceManager.GetObject("multi", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap navigation {
            get {
                object obj = ResourceManager.GetObject("navigation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap navigation_180 {
            get {
                object obj = ResourceManager.GetObject("navigation_180", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Alert Mail was transmitted.({0}) Mail Total: {1}  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string noticeAlertMailSent {
            get {
                return ResourceManager.GetString("noticeAlertMailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alert Mail is enable. Do you read this file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string noticeAlertMailStart {
            get {
                return ResourceManager.GetString("noticeAlertMailStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alert Mail Task End. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string noticeAlertMailTaskEnd {
            get {
                return ResourceManager.GetString("noticeAlertMailTaskEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alert Mail Task Start. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string noticeAlertMailTaskStart {
            get {
                return ResourceManager.GetString("noticeAlertMailTaskStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap plus_circle {
            get {
                object obj = ResourceManager.GetObject("plus_circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Question に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string QuestionMessageBoxTitle {
            get {
                return ResourceManager.GetString("QuestionMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pause(&amp;P) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string reloadToolStripMenuItemPause {
            get {
                return ResourceManager.GetString("reloadToolStripMenuItemPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resume(&amp;R) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string reloadToolStripMenuItemResume {
            get {
                return ResourceManager.GetString("reloadToolStripMenuItemResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap scissors_blue {
            get {
                object obj = ResourceManager.GetObject("scissors_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   (Auto) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusMessageAutoEncoding {
            get {
                return ResourceManager.GetString("StatusMessageAutoEncoding", resourceCulture);
            }
        }
    }
}
